### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by eko24ive** [Artinov/book-search-Qwebeck#2]
Hi @Qwebeck,
Your search is working in strict mode.
Here is what I mean - we have book with name `"Aliquip Culpa Elit"`, I must be able to see this book in search results when I type only `"aliquip"` which is only part of full name of book. For now I see only empty page with no explanation message.
Please fix this

**Comment by Qwebeck** [comment]
Hello erik
I try to fix this problem changing copmare operators`==` and `===`
I rember that `===` operator makes strict compare , so wrote `==` operator
But it doesn' t help and still show book ,only if you wrote full name
Also i try to transform array  with book names into string,then split it for `" "` and compare every new element with form value 
I think it's correct descision but haven't ideas how can continiume this approach

**Comment by eko24ive** [comment]
Have you looked into `.indexOf` method which available both for array and string variables ?

**Comment by Qwebeck** [comment]
Thank you
It helped
Fixed
